### ISSUE TITLE
@conda-forge-admin, please update for conda-build 3

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/uvloop-feedstock#7]
Let's take this for a spin. :)

@conda-forge-admin, please update for conda-build 3.

**Comment by jakirkham** [comment]
@conda-forge-admin, please update for conda-build 3.

**Comment by jakirkham** [comment]
Ran into the following error. Thoughts @conda-forge/core?

```
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 11, column 3:
      fn: -.tar.gz
      ^ (line: 11)
expected <block end>, but found ':'
  in "<unicode string>", line 13, column 3:
      : 
      ^ (line: 13)
```

**Comment by mariusvniekerk** [comment]
Seems like a jinja substitution error?

**Comment by jakirkham** [comment]
Sounds right. It's getting confused by this. Kind of an issue though as this sort of thing is very common.

https://github.com/conda-forge/uvloop-feedstock/blob/d45b791148fcb653884fd8d57ef88faa0e2f119b/recipe/meta.yaml#L11

Also both variables in there are already defined in the recipe, which makes this weird.

https://github.com/conda-forge/uvloop-feedstock/blob/d45b791148fcb653884fd8d57ef88faa0e2f119b/recipe/meta.yaml#L1-L2

**Comment by jakirkham** [comment]
Tracking in issue ( https://github.com/conda-forge/conda-smithy/issues/860 ).

**Comment by jakirkham** [comment]
@conda-forge-admin, please update for conda-build 3.

**Comment by jakirkham** [comment]
@conda-forge-admin, please update for conda-build 3.

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/uvloop-feedstock/pull/9 ).
